receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  batch:
  transform/environment:
    error_mode: ignore
    trace_statements:
      - context: resource
        statements:
          - set(attributes["environment"], "development")
    log_statements:
      - context: resource
        statements:
          - set(attributes["environment"], "development")
    metric_statements:
      - context: resource
        statements:
          - set(attributes["environment"], "development")

exporters:
  debug:
  otlp/aspire:
    endpoint: ${env:ASPIRE_OTLP_ENDPOINT}
    headers:
      x-otlp-api-key: ${env:ASPIRE_API_KEY}
    tls:
      insecure: ${env:ASPIRE_INSECURE}
      insecure_skip_verify: true # Required in local development because cert is localhost and the endpoint is host.docker.internal
  otlphttp/prometheus:
    endpoint: ${env:PROMETHEUS_ENDPOINT}
    tls:
      insecure: true
  otlphttp/loki:
    endpoint: ${env:LOKI_ENDPOINT}
    tls:
      insecure: true
  otlp/tempo:
    endpoint: ${env:TEMPO_URL}
    tls:
      insecure: true
service:
  pipelines:
    logs:
      receivers: [otlp]
      processors:
        - batch
        - transform/environment
      exporters: [otlp/aspire, otlphttp/loki]
    metrics:
      receivers: [otlp]
      processors:
        - batch
        - transform/environment
      exporters: [otlp/aspire, otlphttp/prometheus]
    traces:
      receivers: [otlp]
      processors:
        - batch
        - transform/environment
      exporters: [otlp/aspire, otlp/tempo]
